output_folder: "../logs"
devices: ["cuda:0"]
dataset:
  img_folder: "../data/VOCdevkit/VOC2007/JPEGImages"
  json_folder: "../data"
input:
  img_min_size: [288, 320, 352, 384, 416, 448, 480]
  img_max_size: 640
train_cfg:
  devices: ["cuda:0"]
model:
  backbone: resnet50
  backbone_out_feats_dims: [512, 1024, 2048]
  fpn_feats_dim: 128
opt:
  # 1x schedule: mAP@IoU=0.5 ~61
  epochs: 12
  learing_rate: 0.0025
